// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version SNAPSHOT

== Features

* OC-1749 : Take into account lttd when ack set to OnlyWhenResponseDisabledForUser
* OC-1683 : Always use perimeter when routing cards
+
IMPORTANT: From now, whatever the type(s) of recipient(s), the perimeters are always checked. So if you are using users directly or groups as card recipients, you will now need to add receive rights (Receive or ReceiveAndWrite) for the corresponding process/state of the card.


== Bugs

== Tasks

* OC-1789 : Remove unused btnColor in process.state (businessConfig)
* OC-1687 : Manage Web-UI configuration variants
+
See migration guide for details (//TODO add link once doc is generated)

