// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version SNAPSHOT




== Features
- **UI** : 
** [OC-948][OC-1037] Button to hide or display the timeline
** [OC-949] Filter by publish date in feed when clicking on the clock icon +
**NB:** When the timeline is not loaded (parameter `operatorfabric.feed.timeline.hide` set to true ), the time filter of the feed is based on business date.
** [OC-1038] Incoming cards are signaled as new (little eye icon) in the feed until they've been read
** [OC-1053] For each custom menu entry in the navbar, choose whether to integrate it as an iframe or an external link

[NOTE]
4 new handlebars helpers added: 'keyValue', 'arrayContains', 'times', 'toBreakage'. You can consult the documentation at the following url to check how to use them: https://opfab.github.io/documentation/archives/1.4.0.RELEASE/docs/single_page_doc.html#templates

- **Routing** ([OC-950] [OC-830])  : New routing mechanism is now fully functionnal, it is possible to define card visiblity per process/state for groups using perimeters (see users documentation) 
- **Smart notification** :
**  [OC-918] When receiving a respond card in the UI, integrate the card in the template
**  [OC-915] Front : Activate the possibility of response card depending on user rights && clear the error message in the card details when changing the card.
**  [OC-982] Do not show action & acknowledge button in archive card 
**  [OC-914] control authorizations for /userCard endpoint
**  [OC-966] When delete/update card , delete child cards
**  [OC-980] Action & acknowledge button in bottom right

- ** Acknowlegment ** ([OC-922][OC-923][OC-1033]): It is now possible for the user to acknowlege cards with a button on the bottom-right of the card .The feed can also been filtered to show acknowledged or not acknowledged cards. It is as well possible for the user to "unacknowledge" a card previously acknowlegded .This functionnality is activated on a process state basis via the setting of acknowledgementAllowed to true in the  config.json of the bundles (example in /src/test/utils/karate/src/test/utils/karate/businessconfig/resources/bundle_api_test/config.json)

- ** API ** 
** [OC-934] fix Issue with cards published with client jars (due to Instant). `cards-publication` service accepts cards from client jar.
** [OC-1021] Endpoint do delete user
** [OC-1022] Endpoint to delete entity
** [OC-1023] Endpoint to delete group

== Tasks
- [OC-999] Minor edits to doc after 1rst git flow release 
- [OC-951] Process and state fields of a card must be mandatory
- [OC-1004] Add demo cards and template with svg drawing
- [OC-1005] Clean karate tests
- [OC-1014] Load configuration files from outside docker in `config/docker/docker-compose.yml`
- **Configuration of business process** :
[WARNING]
**Breaking change** : see migration guide

** [OC-978] Rename third module to businessconfig module
** [OC-979] Link bundle with process instead of publisher 
** [OC-1003] Rename processId in processInstanceId
** [OC-981] Change way of creating card id . The id of the card is now build as process.processInstanceId and not anymore publisherID_process.
- [OC-1029] possibility to hide some application menus
- [OC-1036] Refactor configuration loading in front
- [OC-735] Robustify subscription mechanism and refactoring
- [OC-1013] @NotNull fields remove form XXXData.java, only need to set required fields in swagger.yml 
- [OC-1030] : upgrade back to last version of librairies (SpringBoot,..) 
[WARNING]
The version of gradle has been changed, if you want to build operator fabric you need to upgrade gradle to version 6.5.1 (sdk install gradle 6.5.1) 
- [OC-1050] Bumping Java version (minor) to one supported by sdkman
[WARNING]
Run `sdk install java 8.0.262-zulu` then `source ./bin/load_environment_light.sh ` to update your environment
- [OC-1046] Refactoring card-consultation mongo access
- [OC-1045] Remove unnecessary code (ngrx effect )
- [OC-893] Check all subscribe in angular code
- [OC-1047] Add a demo with response card in test/utils 
- [OC-1017] Update governance documentation
- [OC-1057] Explains how to use karate utilities
- [OC-1041] Trace user actions, only acknowledgment for the moment

== Bugs

- [OC-1006] Archives - Bugs in pagination +
**Information :** Parameters `operatorfabric.archive.filter.page.first` & `operatorfabric.archive.filter.publisher` in `web-ui.json` have been removed;
- [OC-990] Automatic saving of the settings . No need anymore to press enter to save setting changes;
- [OC-974] Redraw card when switching between day/night modes;
- [OC-297] Card sent to another group or user is not discarded from the user feed
- [OC-1011] Access to opfab is not working when the user is member of no group
- [OC-1010] In PASSWORD authentication mode, afier having refresh UI, the user needs to enter login/pwd again
- [OC-1035] Docker mode (config/dev) : cards and archivedCards stored in "test" database instead of "operator-fabric"
- [OC-1012] Missing id in existing bundles cause Businessconfig service to crash
- [OC-938] In archives, reset button doesn't really clear selected card
- [OC-988] In Archives- No result message appears before rendering the real result of a search
- [OC-997] Fix Angular build warning
- [OC-941] Card deletion- The API doesn't return an error when the card deleted doesn't exist
- [OC-1052] Cards sent to a user (rather than a group) don't appear immediately
- [OC-713] Web-UI configuration: wrong yaml documented key + misspelled key in configuration
[WARNING]
Need to change in web-ui.json the key delagate-url into delegate-url.


