// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version SNAPSHOT


== Features

- OC-1602: Add delete cards endpoint to delete multiple cards by date criteria

== Bugs

== Tasks

- OC-1630 Adding package-lock.json to git for npm ci

NOTE: From now on, if you want to build the ui
    If you have changed anything in the package.json, use npm install to install/update the dependency and update the package-lock.json accordingly
    If you just want to reproduce the current state of the ui, use npm ci: it will clear node_modules and install dependencies using the versions stated in package-lock.json, ensuring that what your local development environment is identical to what's being built on the CI/CD pipeline.
