
= Version SNAPSHOT

== Issues

* UI Improvements : 
** [OC-868] As an admin I would like to be able to hide the time filter : https://opfab.github.io/documentation/current/deployment/#_web_ui
** [OC-864] As a user I want to be able to reset archives filters so I can change my search criteria
** [OC-402] As an Operator I want the archive screen to display an explicit message if no cards are found that match my filters
** [OC-939] Synchronize timeline with feed (When a filter is set in the feed, it applies as well in the timeline (severity, tags or business period))
** [OC-947] As a user I want to be able to click on the links in the bubble so that i can display the related card on the feed
** [OC-945] Add a spining icon when connection with server is lost
** [OC-972] Add charts functionnality in template +
It uses `charts.js` library, templates as example can be found in `src/test/utils/karate/thirds/resources/bundle_test_api`

* First implementation of "Smart notification" ( [OC-871] [OC-872][OC-874][OC-875][OC-881][OC-900][OC-916][OC-917] )
+
It is now possible for the user to reply to a card, the response is send back to an external app.

+
[IMPORTANT]
====
Work is in progress, it is not documented and usable yet in production. 
====

* Remove old action feature (front and back) ([OC-960][OC-961]) 
+
This feature was not fully operationnal and is now replaced by the smart notification feature

* Remove netflix stack ([OC-670] [OC-836] [OC-838]) :
   - remove registry/configuration components
   - replace gateway with Ngnix 
   - remove all calls  from business services to registry and configuration components

+
[IMPORTANT]
====
UI configuration is now done via a json file (web-ui.json) instead of a yaml file (web-ui.yml).
Before upgrading save a copy of your web-ui.json to back-up custom changes.
====


== Bugs
* [OC-772] Bug on archives screen: clear results when exiting archive page.
* [OC-898] In implicit mode, first name and last name are not displayed
* [OC-775] Cards details remain displayed when selecting another criteria that doesn't return any result

== Tasks
* [OC-892] Add in documentation that it is not possible to use dot in json field names
* [OC-845] Implement Git flow as our contribution and release workflow
+
_We have transitioned from a GitHub flow to a Git flow. See the documentation to see how it impacted our
link:./single_page_doc.html#CICD[CICD pipeline]
and how it translate into our link:./single_page_doc.html#_contribution_workflow[contribution workflow]
(submitting a pull request etc.)._
+
[IMPORTANT]
====
_Now, the current state of developments is pushed daily to Docker Hub with the tag `SNAPSHOT`
(rather than `snapshot` as before)._
====
* [OC-876] User Service : Implement group in JWT Token Option
* [OC-888] Fix SonarCloud Frontend issues
* [OC-692] Fix SonarCloud Backend issues
* [OC-891] Removed unused field mainRecipient
* [OC-899] Deploy and dev-env docker-compose should use SNAPSHOT version on develop branch
+
_When working on branch `develop`, the `deploy` docker-compose will rely on `SNAPSHOT` docker images generated daily.
This lets you test OperatorFabric with the latest merged code. If you're interested in running a particular release on
the other hand, you should checkout the associated X.X.X.RELEASE tag on `master`. The same is true for the
`dev-environment` docker-compose._

* [OC-907] Remove Keycloak from test-quality-environment docker-compose
* [OC-885] User Service : Perimeter model evolution
* [OC-909] Simplify third menu code (Front) 
* [OC-911] Changing sounds due to incompatible license
* [OC-897] Thirds service - added operation delete for the resource thirds
* [OC-904] Thirds service - added delete version of a third, minor changes on general synch working
* [OC-943] Add a gradle task to launch sonar analysis
* [OC-895] External configurations for all services , keycloak and docker-compose files to help with tests and demonstrations
* [OC-924] Correct OpFab doc dead link in Entities section
* link:++https://opfab.atlassian.net/browse/OC-971++[[OC-971]] Update architecture documentation
