// Copyright (c) 2018-2021 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version SNAPSHOT

== Features

* OC-1695 : Add authorized ip address settings in user administration screen
* OC-1723 : UserCard: check that Lttd is not before start date and not after endDate
* OC-1697 : Provide an endpoint to get access to open subscriptions
* OC-1633 : Add the option to filter notifications that has already been answered by user own entity
    
== Bugs

* OC-1711 : Clicking on a link to a third application from a card in modal shall close the modal
* OC-1712 : Screen adjustement for archives screen when resolution smaller than 1920*1080
* OC-1713 : Screen adjustement for logging screen when resolution smaller than 1920*1080
* OC-1722 : Response to card example IT incident is not confirmed
* OC-1728 : Acknowledging all cards shouldn't change their read status
* OC-1716 : Adjustement to view for mobile phone when language is set to french 

== Tasks

* OC-1729 : Removing push_card_loop script (use instead scripts provided in ./src/test/resources) 
* OC-1730 : Fixing baseUrls in swagger for documentation
* OC-1701 : Set indexes in mongoDB
