// Copyright (c) 2018-2020 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Version SNAPSHOT




== Features

- **example** ([OC-XXX] [OC-XXX])  : .... 
- [OC-968] Add UI alert via a clock when ltdd time is approching
- [OC-1056] View card in an agenda style screen
- [OC-1076] Add a filter to see only revelant process in monitoring and logging screen. Revelant processes are configured in the config.json of each process

== Tasks

- [OC-419] Correcting Publication Service Documentation (User Guide)
- [OC-1080] When user has no right to respond to a card , instead of not showing response button , disable it
- [OC-1095] UI - Load i18n for all processes at startup
- [OC-1097] Remove unused vps env configuration
- [OC-1082] UI - Remove use of method askUserApplicationRegistered
- [OC-1072] UI - Load All Entities information in the UI when user is starting OpFab 
- [OC-867] UI - Change time filter label, depending on the timeline hidden or not
- [OC-1094] Add write access for defaultprocess with state message in standard config and bundle cleaning
- [OC-1096] Add an heardbeat mechanism to the SSE connection to avoid setting long timeout in nginx and to be compatible with the use of external proxies


== Bugs

